### ISSUE TITLE
ImportError: No module named magic 

### ISSUE THREAD

**Issue by saivasanth** [wheelerda/extract-mbz#1]
Hi

i have tried your python script for extract the files from my moodle backup file , i am getting below error pls help me 

root@boss[moodle2-file-extractor-master]#python mbz-extract.py backup-moodle2-course-2-csc-20170613-0747.mbz 
Traceback (most recent call last):
  File "mbz-extract.py", line 2, in <module>
    import mbz
  File "/var/www/html/moodle2-file-extractor-master/mbz.py", line 12, in <module>
    import magic
ImportError: No module named magic

**Comment by wheelerda** [comment]
I can't replicate this yet (I don't use magic so one of the other libraries must). What are the specs for the system where you are running this? Looks like Linux. python --version ? 

...dan

**Comment by wheelerda** [comment]
I see that there is an update to my original here - https://github.com/Swarthmore/extract-mbz - which might possibly work for you. Worth a try. 

...dan
